version: '3.8'
services:
  RTRdb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: p4ssword
      MYSQL_DATABASE: Comments
      MYSQL_USER: user
    ports:
      - "3322:3306"
    volumes:
      - RTR-db:/var/lib/mysql
    networks: 
      - ggc-network
  # rtr-app:
  #   depends_on:
  #     - "RTRdb"
  #   image: ghcr.io/fontys-s6-maatwerk/rtrapp:develop
  #   restart: always
  #   ports:
  #     - "9090:80"
  #   networks: 
  #     - ggc-network
  rtr-gateway:
    depends_on:
      - "RTRdb"
    image: ghcr.io/fontys-s6-maatwerk/rtrgateway:main
    restart: always
    ports:
      - "9092:80"
    networks: 
      - ggc-network

  solution-service: 
    image: ghcr.io/fontys-s6-maatwerk/solutionsservice:main
    hostname: solution-service
    container_name: solution-service
    ports:
      - "5000:80"
    depends_on:
      - sol_db
    networks: 
      - ggc-network
    restart: unless-stopped
  
  comment-service:
    depends_on:
      - "RTRdb"
    image: ghcr.io/fontys-s6-maatwerk/commentservice:main
    restart: always
    ports:
      - "9094:80"
    networks: 
      - ggc-network

  ocelot-gateway:
    image: ghcr.io/fontys-s6-maatwerk/ggcgateway:main
    hostname: ocelot-gateway
    container_name: ocelot-gateway
    ports:
      - "5011:80"
    depends_on:
      - solution-service
    networks: 
      - ggc-network
    restart: unless-stopped

  sol_db:
    image: "mcr.microsoft.com/mssql/server"
    volumes:
      - sol_volume:/var/opt/mssql
    container_name: sol_db

    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
     - "1433"
     - "1001:1433"
    networks: 
     - ggc-network
    restart: unless-stopped

  # db:
  #   platform: linux/x86_64
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: fontys
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - db-data:/var/lib/mysql
  #   networks:
  #     - ggc-network
  # api:
  #   depends_on: ["db"]
  #   image: ghcr.io/fontys-s6-maatwerk/userservice:main
  #   restart: always
  #   ports:
  #     - "80:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - DB_HOST=db
  #     - DB_USERNAME=root
  #     - DB_PASSWORD=root
  #     - DB_NAME=fontys
  #   networks:
  #     - ggc-network

  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   container_name: 'messaging'
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   networks:
  #     - ggc-networks


volumes:
  RTR-db:
  sol_volume:
  db-data:

networks:
  ggc-network:
    external: true