version: '3.8'
services:
  RTRdb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: p4ssword
      MYSQL_DATABASE: Comments
      MYSQL_USER: user
    ports:
      - "3322:3306"
    volumes:
      - RTR-db:/var/lib/mysql
    networks: 
      - ggc-network
  # rtr-app:
  #   depends_on:
  #     - "RTRdb"
  #   image: ghcr.io/fontys-s6-maatwerk/rtrapp:develop
  #   restart: always
  #   ports:
  #     - "9090:80"
  #   networks: 
  #     - ggc-network
  rtr-gateway:
    depends_on:
      - "RTRdb"
    image: ghcr.io/fontys-s6-maatwerk/rtrgateway:main
    restart: always
    ports:
      - "9092:80"
    networks: 
      - ggc-network

  solution-service: 
    image: ghcr.io/fontys-s6-maatwerk/solutionsservice:main
    hostname: solution-service
    container_name: solution-service
    ports:
      - "5000:80"
    depends_on:
      - sol_db
    networks: 
      - ggc-network
    restart: unless-stopped
  
  comment-service:
    depends_on:
      - "RTRdb"
    image: ghcr.io/fontys-s6-maatwerk/commentservice:main
    restart: always
    ports:
      - "9094:80"
    networks: 
      - ggc-network

  ocelot-gateway:
    image: ghcr.io/fontys-s6-maatwerk/ggcgateway:main
    hostname: ocelot-gateway
    container_name: ocelot-gateway
    ports:
      - "5011:80"
    depends_on:
      - solution-service
    networks: 
      - ggc-network
    restart: unless-stopped

  sol_db:
    image: "mcr.microsoft.com/mssql/server"
    volumes:
      - sol_volume:/var/opt/mssql
    container_name: sol_db

    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
     - "1433"
     - "1001:1433"
    networks: 
     - ggc-network
    restart: unless-stopped

volumes:
  RTR-db:
  sol_volume:

networks:
  ggc-network:
    external: true