version: "3.6"

services:
  authentication-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: authentication
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - authentication-db-data:/var/lib/mysql
  authentication-service:
    image: authentication-service
    restart: always
    build:
      context: ./AuthenticationService

volumes:
  authentication-db-data: